#in case of directory: make sure to end with "/"

TE_vs_TE_folder: "/your/path/" 
out_dir: "/your/path/"
prot_domain_loc_hmm: "/your/path/" #output from TE_extraction
prot_domain_loc_rps: "/your/path/" #output from TE_extraction
te_translated_orf_loc: "/your/path/" #output from TE_extraction
fasta_loc: "/your/path/"
quantile_file: "/home/josje/scripts/BUSCO_Ks_tree_nodes/all_sp_sp_combinations.txt"
